In [1]:
import pandas as pd

In [5]:
netflix = pd.read_csv('netflix.csv')

In [6]:
netflix.head()

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [ ]:
# cikis tarihine gore siralama yapalim ve ilk cikanlar yukarida olsun

netflix.sort_values(
    by,
    axis: 'Axis' = 0,
    ascending=True,
    inplace: 'bool' = False,
    kind: 'str' = 'quicksort',
    na_position: 'str' = 'last',
    ignore_index: 'bool' = False,
    key: 'ValueKeyFunc' = None,
)

In [8]:
netflix.sort_values('cikis_tarihi').head()

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
4292,81030762,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,1 Season,TV Shows,This collection restores films from women who ...
2011,60027945,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
2013,60027942,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
2022,80119186,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
2023,70013050,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,82 min,Documentaries,This installment of Frank Capra's acclaimed do...

In [9]:
netflix.sort_values('cikis_tarihi', ascending=False).head()

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
3467,81011449,TV Show,Medical Police,NaN,"Erinn Hayes, Rob Huebel, Malin Akerman, Rob Co...",United States,"January 10, 2020",2020,1 Season,"Crime TV Shows, TV Action & Adventure, TV Come...",Doctors Owen Maestro and Lola Spratt leave Chi...
3249,81006825,Movie,All the Freckles in the World,Yibrán Asuad,"Hánssel Casillas, Loreto Peralta, Andrea Sutto...",Mexico,"January 3, 2020",2020,90 min,"Comedies, International Movies, Romantic Movies",Thirteen-year-old José Miguel is immune to 199...
3220,80997687,TV Show,Dracula,NaN,"Claes Bang, Dolly Wells, John Heffernan",United Kingdom,"January 4, 2020",2020,1 Season,"British TV Shows, International TV Shows, TV D...",The Count Dracula legend transforms with new t...
3427,81060049,Movie,Leslie Jones: Time Machine,"David Benioff, D.B. Weiss",Leslie Jones,United States,"January 14, 2020",2020,66 min,Stand-Up Comedy,From trying to seduce Prince to battling sleep...
3436,80239306,TV Show,The Healing Powers of Dude,NaN,"Jace Chapman, Larisa Oleynik, Tom Everett Scot...",NaN,"January 13, 2020",2020,1 Season,"Kids' TV, TV Comedies, TV Dramas",When an 11-year-old boy with social anxiety di...

In [11]:
netflix.sort_values('ulke', ascending=True).head()

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
532,81105406,TV Show,Monzón: A Knockout Blow,NaN,"Jorge Román, Mauricio Paniagua, Carla Quevedo,...",Argentina,"October 25, 2019",2018,1 Season,"Crime TV Shows, International TV Shows, Spanis...",This dramatization tells the story of Argentin...
6210,80239700,TV Show,Psiconautas,NaN,"Guillermo Toledo, Gabriel Goity, Florencia Peñ...",Argentina,"April 15, 2018",2016,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",A Spanish con man masquerades as a therapist a...
4075,80156767,Movie,La Última Fiesta,"Leandro Mark, Nicolás Silbert","Nicolás Vázquez, Alan Sabbagh, Benjamín Amadeo...",Argentina,"February 1, 2017",2016,104 min,"Comedies, International Movies",Three best buddies are thrown into a wild chas...
398,80190990,Movie,Todo Sobre El Asado,"Mariano Cohn, Gastón Duprat",El Negro Álvarez,Argentina,"September 1, 2017",2016,86 min,"Documentaries, International Movies",This quirky examination of Argentina's culture...
4422,80142140,Movie,Daemonium,Pablo Parés,"Walter Cornás, Dany Casco, Caro Angus, Rocío R...",Argentina,"December 20, 2016",2015,115 min,"Action & Adventure, Horror Movies, Internation...",In a realm where magic and technology intersec...

In [13]:
netflix.sort_index().head()

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,99 min,Comedies,When nerdy high schooler Dani finally attracts...